- triggers:
    - trigger: time_pattern
      seconds: "/5"
  sensor:
    - name: VRM Installations
      unique_id: vrm_installations
      icon: mdi:solar-power-variant
      state: >-
        {{ states | selectattr('entity_id', 'match', '^sensor\.vrm_.+_custom_aggregate_ac_grid_power$') | list | length }}
      attributes:
        installations: >-
          {% set ns = namespace(items=[]) %}
          {% for s in states | selectattr('entity_id', 'match', '^sensor\.vrm_.+_custom_aggregate_ac_grid_power$') | list %}
            {% set eid = s.entity_id %}
            {% set portal = eid.split('_')[1] %}
            {% set id = 'vrm_' ~ portal %}
            {% set soc   = states('sensor.' ~ id ~ '_system_0_dc_battery_soc')                    | float(0) %}
            {% set battery_voltage = states('sensor.' ~ id ~ '_system_0_dc_battery_voltage')      | float(0) %}
            {% set pv = states('sensor.' ~ id ~ '_custom_aggregate_pv_power')                     | float(0) %}
            {% set grid  = states('sensor.' ~ id ~ '_custom_aggregate_ac_grid_power')             | float(0) %}
            {% set gens  = states('sensor.' ~ id ~ '_custom_aggregate_ac_genset_power')           | float(0) %}
            {% set load  = states('sensor.' ~ id ~ '_custom_aggregate_ac_consumption_power')      | float(0) %}
            {% set name  = device_attr(eid, 'name') or portal %}
            {% set online = is_state('sensor.' ~ id ~ '_custom_aggregate_ac_grid_power', 'unavailable') == false %}
            {% set ns.items = ns.items + [{
              'id':               eid,
              'name':             name,
              'online':           online,
              'soc':              soc,
              'battery_voltage':  battery_voltage,
              'pv':               pv,
              'grid':             grid,
              'genset':           gens,
              'load':             load
            }] %}
          {% endfor %}
          {{ {'installations': ns.items} | to_json }}