- triggers:
    - trigger: time_pattern
      seconds: "/5"
  sensor:
    - name: VRM Installations
      unique_id: vrm_installations
      icon: mdi:solar-power-variant
      state: >-
        {{ states | selectattr('entity_id', 'match', '^sensor\.vrm_.+_system_0_ac_grid_aggpower$') | list | length }}
      attributes:
        installations: >-
          {% set ns = namespace(items=[]) %}
          {% for s in states | selectattr('entity_id', 'match', '^sensor\.vrm_.+_system_0_ac_grid_aggpower$') | list %}
            {% set eid = s.entity_id %}
            {% set portal = eid.split('_')[1] %}
            {% set id = 'vrm_' ~ portal %}
            {% set dc_pv = states('sensor.' ~ id ~ '_system_0_dc_pv_power')                   | float(0) %}
            {% set on_output_pv = states('sensor.' ~ id ~ '_system_0_ac_pvonoutput_aggpower') | float(0) %}
            {% if on_output_pv < 0 %}
              {% set on_output_pv = 0 %}
            {% endif %}
            {% set on_grid_pv = states('sensor.' ~ id ~ '_system_0_ac_pvongrid_aggpower')     | float(0) %}
            {% if on_grid_pv < 0 %}
              {% set on_grid_pv = 0 %}
            {% endif %}
            {% set pv = dc_pv + on_grid_pv %}
            {% set soc   = states('sensor.' ~ id ~ '_system_0_dc_battery_soc')                | float(0) %}
            {% set battery_voltage = states('sensor.' ~ id ~ '_system_0_dc_battery_voltage')  | float(0) %}
            {% set grid  = states('sensor.' ~ id ~ '_system_0_ac_grid_aggpower')              | float(0) %}
            {% set gens  = states('sensor.' ~ id ~ '_system_0_ac_genset_aggpower')            | float(0) %}
            {% set load  = states('sensor.' ~ id ~ '_system_0_ac_consumption_aggpower')       | float(0) %}
            {% set name  = device_attr(eid, 'name') or portal %}
            {% set ns.items = ns.items + [{
              'name':             name,
              'soc':              soc,
              'battery_voltage':  battery_voltage,
              'pv':               pv,
              'grid':             grid,
              'genset':           gens,
              'load':             load
            }] %}
          {% endfor %}
          {{ {'installations': ns.items} | to_json }}